### ISSUE TITLE
Fail to build by Dockerfile CI

### ISSUE THREAD

**Issue by harryprince** [road2stat/imgsvd#5]
---> Running in 83bcde32ec62
2016-06-10 05:27:36 URL:https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/VERSION [10/10] -> "version.txt" [1]
2016-06-10 05:27:43 URL:https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/shiny-server-1.4.2.789-amd64.deb [53648754/53648754] -> "ss-latest.deb" [1]
Traceback (most recent call last):
File "/usr/bin/gdebi", line 38, in <module>
from GDebi.GDebiCli import GDebiCli
File "/usr/share/gdebi/GDebi/GDebiCli.py", line 24, in <module>
import apt
ImportError: No module named 'apt'
Removing intermediate container 83bcde32ec62
The command '/bin/sh -c wget --no-verbose https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/VERSION -O "version.txt" && VERSION=$(cat version.txt) && wget --no-verbose "https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/shiny-server-$VERSION-amd64.deb" -O ss-latest.deb && gdebi -n ss-latest.deb && rm -f version.txt ss-latest.deb && R -e "install.packages(c('shiny', 'rmarkdown', 'devtools', 'roxygen2'), repos='https://cran.rstudio.com/')"' returned a non-zero code: 1

**Comment by road2stat** [comment]
This might belong to: https://github.com/thirdwing/mxnet_shiny
